databases:
  - name: django_authdb
    plan: free
    databaseName: django_auth
    user: django_auth

services:
  - type: web
    plan: free
    name: django_auth
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn django_auth_api.asgi:application -k uvicorn.workers.UvicornWorke"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_authdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
